# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Tic Tac Toe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Database'
pod 'lottie-ios'
  # Pods for Tic Tac Toe

  target 'Tic Tac ToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tic Tac ToeUITests' do
    # Pods for testing
  end

end
